[versions]
agp = "8.5.2"
kotlin = "1.9.24"
compileSdk = "35"
minSdk = "23"
targetSdk = "35"

coreKtx = "1.12.0"
lifecycleRuntime = "2.7.0"
coroutines = "1.7.3"
navigation = "2.7.7"

firebaseBom = "33.5.1"
credentials = "1.5.0"
googleid = "1.1.0"

recyclerview = "1.3.2"
cardview = "1.0.0"
material = "1.11.0"

espresso = "3.5.1"
junitExt = "1.1.5"
junitVersion = "4.13.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-activity = { module = "androidx.activity:activity-ktx", version = "1.8.2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }

material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }

# Navigation
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

# Lifecycles / Coroutines
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-database = { module = "com.google.firebase:firebase-database-ktx" }

# Google Sign-In / Credentials
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

# Testing
junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid     = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices    = { id = "com.google.gms.google-services", version = "4.4.2" }